const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("index.html", "utf8");
const css = fs.readFileSync("styles.css", "utf8");

assert.match(html, /viewport-fit=cover/, "safe areaを考慮したviewport設定がある");
assert.match(css, /max-width:\s*430px/, "スマホ幅を基準にしたアプリシェル幅がある");
assert.match(css, /env\(safe-area-inset-bottom\)/, "iPhone下部safe areaの余白を考慮している");
assert.match(css, /word-break:\s*keep-all/, "日本語ラベルの不自然な文字分割を避ける指定がある");
assert.match(css, /line-break:\s*strict/, "日本語改行ルールの指定がある");
assert.match(css, /@media\s*\(max-width:\s*380px\)/, "小さめスマホ向けの調整がある");
assert.match(html, /id="archiveSearchInput"/, "保存済み試合の検索欄がある");
assert.match(html, /id="archiveDateFilterSelect"/, "保存済み試合の日付絞り込みがある");
assert.match(html, /id="archiveTypeFilterSelect"/, "保存済み試合の種目絞り込みがある");
assert.match(html, /id="archiveStatusFilterSelect"/, "保存済み試合の状態絞り込みがある");
assert.match(html, /id="archiveResultFilterSelect"/, "保存済み試合の勝敗絞り込みがある");
assert.match(html, /id="archiveTournamentFilterSelect"/, "保存済み試合の大会絞り込みがある");
assert.match(html, /id="archiveSortSelect"/, "保存済み試合の並び替えがある");
assert.match(html, /id="archiveCountLabel"/, "保存済み試合の件数表示がある");
assert.match(html, /id="archiveStorageLabel"/, "保存容量の目安表示がある");
assert.match(html, /端末引き継ぎ[\s\S]*id="exportBackupButton"[\s\S]*id="importBackupButton"/, "端末引き継ぎメニューから試合データを保存・読み込みできる");
assert.match(html, /id="exportArchivedCsvButton"/, "管理用メニューから保存した試合CSVを一括出力できる");
assert.doesNotMatch(html, /id="archiveExportCsvButton"/, "保存済み試合画面には管理用CSVボタンを出さない");
assert.match(html, /id="summaryModeControl"/, "サマリー画像の用途切替がある");
assert.doesNotMatch(html, /saveCurrentMatchButton|今の試合を保存/, "手動の試合保存ボタンを出さない");
assert.match(html, /記録した試合は自動保存されます/, "メニューで自動保存を伝える");
assert.match(css, /\.action-history::before[\s\S]*content:\s*"試"/, "保存済み試合のアイコンを区別する");
assert.match(html, /id="summaryNameModeControl"/, "チーム共有用サマリーの表示名切替がある");
assert.match(html, /役割のみ[\s\S]*チーム名あり[\s\S]*名前あり/, "表示名を3段階で選べる");
assert.match(css, /\.summary-name-mode/, "表示名切替のCSSがある");
assert.match(html, /入力1 サービス側[\s\S]*入力2 サービス結果[\s\S]*入力3 誰のプレー[\s\S]*自動判定（必要なら修正）[\s\S]*入力4 ポイントの決まり方[\s\S]*得点になったプレー[\s\S]*ストローク[\s\S]*打ち合い[\s\S]*ミスになったプレー[\s\S]*入力5 ラリーの長さ[\s\S]*3本以内[\s\S]*4本以上[\s\S]*入力6 得点した側を押して保存/, "かんたん入力は試合中に押す順で表示する");
assert.match(css, /simple-outcome-control \.outcome-score\.active[\s\S]*var\(--own\)/, "得点系プレー結果の選択色がある");
assert.match(css, /simple-outcome-control \.outcome-miss\.active[\s\S]*var\(--opp\)/, "ミス系プレー結果の選択色がある");
assert.match(html, /class="winner-note"[\s\S]*相手のミスなら「自チーム」/, "得点側保存の迷いを減らす補足がある");
assert.match(css, /\.save-point-section\s*\{[\s\S]*position:\s*sticky/, "得点保存ボタンが押しやすい位置に残る");
assert.match(css, /#summaryImageDialog[\s\S]*height:\s*min\(96dvh,[\s\S]*height:\s*min\(96svh,[\s\S]*@media \(max-width:\s*640px\)[\s\S]*#summaryImageDialog[\s\S]*height:\s*100svh/, "サマリー画像画面はスマホで画面いっぱいに表示する");
assert.match(css, /\.summary-preview-frame[\s\S]*overflow-y:\s*auto[\s\S]*-webkit-overflow-scrolling:\s*touch/, "サマリー画像プレビュー内を縦スクロールできる");
assert.match(fs.readFileSync("app.js", "utf8"), /const drawScoreBoard = \(y\) => [\s\S]*return y \+ 286;/, "試合結果枠と次の見出しに十分な余白を残す");
assert.match(fs.readFileSync("app.js", "utf8"), /setSummaryPreviewMode[\s\S]*summaryPreviewFrame\?\.scrollTo\?\.\(\{ top: 0, left: 0 \}\)/, "サマリー画像の用途切替時に先頭へ戻す");
assert.doesNotMatch(html, /拡大して確認|summaryPreviewZoomControl|data-summary-zoom/, "サマリー画像画面に拡大切替ボタンを出さない");
assert.match(css, /\.summary-dialog \.dialog-actions\s*\{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/, "サマリー画像画面の主要ボタンはスマホで2列表示になる");
assert.match(css, /\.summary-dialog \.dialog-actions \.action-close\s*\{[\s\S]*grid-column:\s*1 \/ -1/, "サマリー画像画面の閉じるボタンは下段全幅になる");
assert.match(html, /app-config\.js\?v=210[\s\S]*app-analysis\.js\?v=210[\s\S]*app-storage\.js\?v=210[\s\S]*app-rules\.js\?v=210[\s\S]*app\.js\?v=210/, "設定、分析、保存、ルール、本体の順に読み込む");
assert.match(html, /styles\.css\?v=210/, "styles.cssのキャッシュ更新バージョンが最新");
assert.match(fs.readFileSync("sw.js", "utf8"), /soft-tennis-logger-v210/, "Service Workerのキャッシュ名が最新");
assert.match(fs.readFileSync("sw.js", "utf8"), /app-config\.js/, "Service Workerのキャッシュ対象に設定ファイルがある");
assert.match(fs.readFileSync("sw.js", "utf8"), /app-analysis\.js/, "Service Workerのキャッシュ対象に分析ファイルがある");
assert.match(fs.readFileSync("sw.js", "utf8"), /app-storage\.js/, "Service Workerのキャッシュ対象に保存ファイルがある");
assert.match(fs.readFileSync("sw.js", "utf8"), /app-rules\.js/, "Service Workerのキャッシュ対象にルールファイルがある");

assert.match(html, /class="match-dialog-section match-dialog-essential"[\s\S]*最低限の試合情報/, "試合情報編集に最低限の試合情報セクションがある");
assert.match(html, /<details class="match-dialog-section match-dialog-optional">[\s\S]*<summary>追加項目<\/summary>/, "試合情報編集に折りたたみの追加項目がある");
assert.match(css, /scroll-padding-bottom:\s*calc\(88px \+ env\(safe-area-inset-bottom\)\)/, "キーボード表示時も下部操作へスクロール余白を確保する");
assert.match(html, /id="dialogTeamA"[^>]*enterkeyhint="next"/, "チーム名入力にスマホキーボードの次へヒントがある");
assert.match(html, /id="venueInput"[^>]*enterkeyhint="done"/, "最後の入力欄に完了ヒントがある");

assert.match(html, /<summary>自動判定（必要なら修正）<\/summary>/, "サーブ・レシーブした人は自動判定から必要時に修正できる");
assert.match(html, /<span>サーブした人<\/span>[\s\S]*id="serverPlayerControl"/, "必要時にサーブした人を修正できる");
assert.match(html, /<span>レシーブした人<\/span>[\s\S]*id="receiverPlayerControl"/, "必要時にレシーブした人を修正できる");
assert.doesNotMatch(html, /service-player-group advanced-record/, "サーブ・レシーブ選手は詳細専用にしない");
assert.match(html, /data-simple-outcome="ダブルフォールト"[\s\S]*data-simple-outcome="レシーブミス"[\s\S]*data-simple-outcome="ストロークミス"/, "かんたん記録のミスはDF・レシーブ・ストロークの順に選べる");
assert.match(html, /data-simple-outcome="レシーブミス"[^>]*>[\s\S]*<span>レシーブ<\/span>[\s\S]*<small>ミス<\/small>/, "レシーブミスは短い2行表示にする");
assert.doesNotMatch(html, /data-simple-outcome="ボレー得点"[^>]*>[\s\S]*<small>前衛<\/small>/, "ボレー得点を前衛専用に見せない");
assert.match(html, /data-simple-outcome="サービス得点"[\s\S]*data-simple-outcome="レシーブ得点"[\s\S]*data-simple-outcome="ストローク得点"/, "かんたん記録の得点はサーブ・レシーブ・ストロークの順に選べる");
assert.match(html, /data-simple-outcome="ボレー得点"[\s\S]*data-simple-outcome="スマッシュ得点"/, "かんたん記録でボレー・スマッシュの得点を選べる");
assert.match(html, /data-simple-outcome="ボレーミス"[\s\S]*data-simple-outcome="スマッシュミス"/, "かんたん記録でボレー・スマッシュのミスを選べる");
assert.doesNotMatch(fs.readFileSync("app.js", "utf8"), /function inferFrontPlayPlayer/, "ボレー・スマッシュでも未選択時に前衛へ自動補助しない");
assert.match(html, /id="analysisSectionControl"[\s\S]*data-analysis-section="overall"[\s\S]*data-analysis-section="players"/, "分析画面に全体分析/個人別分析切り替えがある");
assert.doesNotMatch(html, /id="standardGrowthBoard"|data-analysis-mode="standard"|data-analysis-mode="detail"/, "分析画面に旧標準/詳細表示を残さない");
assert.match(html, /class="analysis-section analysis-overall-section"[\s\S]*得点しやすい場面[\s\S]*失点しやすい場面[\s\S]*ラリーの長さ[\s\S]*class="analysis-section analysis-player-section"[\s\S]*選手別 成長メモ[\s\S]*選手別 サーブ\/レシーブ[\s\S]*個人別コメントを保存/, "分析画面は全体分析を数字中心、個人別分析をコメント中心に分ける");
assert.doesNotMatch(html, /id="opponentView"|id="actionPlan"/, "全体分析にチーム単位コメント枠を出さない");
assert.doesNotMatch(html, /短く見るポイント|id="coachNotes"/, "分析画面に短く見るポイント枠を出さない");
assert.doesNotMatch(html, /次に攻めたい相手ミス|opponentErrorBars/, "次に攻めたい相手ミスの独立枠を出さない");
assert.match(css, /#analysisPanel \.chart-block > h2[\s\S]*font-size:\s*0\.94rem/, "分析画面の項目タイトルサイズを統一する");
assert.match(css, /\.analysis-section[\s\S]*analysis-overall-mode[\s\S]*analysis-player-mode/, "分析画面に全体分析/個人別分析切り替えのCSSがある");
assert.match(css, /\.serve-receive-cards/, "選手別S/RカードのCSSがある");
assert.match(css, /\.sr-side-group[\s\S]*\.own-side[\s\S]*\.opp-side/, "選手別S/R分析も自チームと相手を視覚的に分ける");
assert.match(html, /選手別 サーブ\/レシーブ[\s\S]*サービス順と初期設定をもとに/, "分析画面でS/R担当の自動判定を説明する");
assert.match(html, /class="record-top-grid"[\s\S]*入力1 サービス側[\s\S]*入力2 サービス結果/, "記録画面の上段入力はサービス側と結果を並べて表示する");
assert.match(html, /class="control-group player-record-group"[\s\S]*入力3 誰のプレー[\s\S]*id="playerSavePreview"/, "かんたん記録で誰として保存されるか確認できる");
assert.match(css, /\.player-save-preview/, "保存される選手の補助表示CSSがある");
assert.match(html, /id="rallyLengthControl"[\s\S]*data-rally-length="short"[\s\S]*data-rally-length="long"/, "ラリーの長さを3本以内・4本以上で選べる");
assert.doesNotMatch(html, /data-rally-length="auto"/, "ラリー長さの自動ボタンは出さない");
assert.match(html, /ラリーの長さ[\s\S]*サーブを1本目として、3本以内か4本以上かを確認/, "分析画面でラリーの長さを確認できる");
assert.match(css, /\.record-top-grid[\s\S]*border-left:[\s\S]*rgba\(37, 99, 235, 0\.42\)/, "入力1-2のまとまりに軽い境界線がある");
assert.match(css, /\.player-record-group,[\s\S]*\.simple-record-group[\s\S]*border-left:[\s\S]*rgba\(37, 99, 235, 0\.42\)/, "入力3以降もステップの境界がある");
assert.match(css, /\.rally-record-group[\s\S]*border-left:[\s\S]*rgba\(37, 99, 235, 0\.42\)[\s\S]*\.rally-length-control/, "ラリー長さ入力のCSSがある");
assert.match(html, /選手別 成長メモ[\s\S]*選手ごとの \+ \/ - と、記録したプレー種別/, "選手別分析でプレー種別を見る意図を説明する");
assert.match(css, /\.pm-side-group[\s\S]*\.own-side[\s\S]*\.opp-side/, "選手別分析は自チームと相手を視覚的に分ける");
assert.match(css, /\.pm-detail-grid/, "プレイヤー別カードで決まり方とプレー別を分けて表示する");
assert.match(css, /\.pm-review/, "プレイヤー別カードに記録から分かることを表示するCSSがある");
assert.match(css, /\.pm-total-badge[\s\S]*font-weight:\s*1000/, "個人別+/-の合計値を強調表示する");
assert.match(css, /\.archive-item \.action-button[\s\S]*white-space:\s*nowrap/, "保存済み試合のボタンは短い表示で見切れにくくする");
assert.match(css, /\.archive-item \.action-preview[\s\S]*grid-column:\s*1 \/ -1/, "スマホでは保存済み試合の画像ボタンを全幅にする");
assert.match(html, /流れと勝負どころ[\s\S]*発生したゲームとカウント付きで確認/, "流れと勝負どころに具体場面の説明がある");
assert.doesNotMatch(html, /数字の見方|ボールの到達位置[\s\S]*id="courseBars"|フォア\/バックの傾向|ネット\/アウトの内訳/, "試合後に詳しく見る内の低利用項目を出さない");
assert.match(css, /\.momentum-list[\s\S]*\.momentum-card/, "流れと勝負どころはカード表示CSSがある");
assert.match(css, /\.momentum-card small/, "流れと勝負どころに発生場面を表示するCSSがある");
assert.doesNotMatch(html, /class="control-group advanced-record"[\s\S]{0,80}<span>誰のプレー<\/span>/, "誰のプレーは詳細専用にしない");

console.log("responsive-static: ok");
